[workspace]
members = [
    "crates/player_widget",
    "crates/shaders",
    "crates/app",
]
resolver = "3"

[workspace.dependencies]
iced = { version = "0.14", features = ["image", "advanced", "wgpu"] }
iced_wgpu = "0.14"
gstreamer = "0.23"
gstreamer-app = "0.23"
gstreamer-base = "0.23"
gstreamer-video = "0.23"
glib = "0.20"
log = "0.4"
thiserror = "1"
url = "2"
