[package]
name = "iced_video_player"
description = "A convenient video player widget for Iced"
homepage = "https://github.com/jazzfool/iced_video_player"
repository = "https://github.com/jazzfool/iced_video_player"
readme = "README.md"
keywords = ["gui", "iced", "video"]
categories = ["gui", "multimedia"]
version = "0.6.0"
authors = ["jazzfool"]
edition = "2024"
resolver = "2"
license = "MIT OR Apache-2.0"
exclude = [
    ".media/test.mp4"
]

[dependencies]
iced-video-shaders = { path = "../shaders" }
iced.workspace = true
iced_wgpu.workspace = true
gstreamer.workspace = true
gstreamer-app.workspace = true
gstreamer-base.workspace = true
gstreamer-video.workspace = true
glib.workspace = true
log.workspace = true
thiserror.workspace = true
url.workspace = true
